version: "3.9"

services:
  cdk-constructs:
    build:
      context: .
    volumes:
      - ${HOME}/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - NODE_ENV=${NODE_ENV}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - ACCOUNT_NAME=${ACCOUNT_NAME}
